### ISSUE TITLE
What does config in values do?

### ISSUE THREAD

**Issue by jbrardport** [softonic/go-ratelimit-chart#11]
https://github.com/softonic/go-ratelimit-chart/blob/master/values.yaml#L67

Doesn't seem to be referenced anywhere and does not interact with the configmap for the deployment.

https://github.com/softonic/go-ratelimit-chart/blob/master/templates/configmap.yaml

**Comment by santinoncs** [comment]
you are right. Thanks for the comment. You can maybe request a PR ?
