### ISSUE TITLE
README Deployment instructions not working

### ISSUE THREAD

**Issue by mehyedes** [softonic/go-ratelimit-chart#6]
When trying to install the helm chart following the README instructions, I got the following errors:
```bash
helm install redis-sharded softonic/go-ratelimit-chart
Error: failed to download "softonic/go-ratelimit-chart" (hint: running `helm repo update` may help)
```
Besides, the release name that is used here is misleading, `redis-sharded` is used while it should be maybe `rate-limiter` or something similar.
Using `helm search`, it looks like the chart name is wrong:
```bash
helm search repo ratelimit
NAME                 	CHART VERSION	APP VERSION	DESCRIPTION
softonic/go-ratelimit	1.0.2        	1.5.0      	A Ratelimit Service Helm chart for Kubernetes
```

Fixing the chart name causes another error related to the redis-sharded chart dependency though:
```bash
helm install rate-limiter softonic/go-ratelimit
Error: found in Chart.yaml, but missing in charts/ directory: redis-sharded
```
The redis chart in this case needs to either be packaged with the rate-limiter chart, or to be installed independently before installing rate limiter.

**Comment by santinoncs** [comment]
Thanks for your insight, let me modify this 
appreciate

**Comment by mehyedes** [comment]
Hey @santinoncs , thank you for sharing this helm chart and for your quick response 🤝  
Much appreciated :)

**Comment by mehyedes** [comment]
I have also noticed that there is no docker image tagged `v1.5.0` available, so the default `appVersion` value is not working.
There is only `master` or `v1.4.0`:
https://hub.docker.com/r/envoyproxy/ratelimit/tags?page=1&ordering=last_updated&name=v1

**Comment by santinoncs** [comment]
> I have also noticed that there is no docker image tagged `v1.5.0` available, so the default `appVersion` value is not working.
> There is only `master` or `v1.4.0`:
> https://hub.docker.com/r/envoyproxy/ratelimit/tags?page=1&ordering=last_updated&name=v1


I needed to modify the image so the image is not in docker, it is here

softonic/ratelimit:1.5.0

in docker hub

Let me modify this in values.yaml

**Comment by mehyedes** [comment]
Aha I see, that explains.
